"use client";

import Editor from './LexicalEditor';
import './globals.css'
import { Inter } from 'next/font/google'
import { useState } from "react";
import SplitPane, { Pane } from 'split-pane-react';
import 'split-pane-react/esm/themes/default.css'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  
  const [sizes, setSizes] = useState([
      '40%',
      '60%',
      // 'auto',
  ]);

  const layoutCSS = {
      height: '100%',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ height: '100vh' }}>
              {children}
          </div>
      </body>
    </html>
  )
}
